$(document).ready(function(){
    $("#signup-form").validate({
       rules:{
        fname:{
            required:true,
            minlength:4,
            maxlength:10
        },
        sname:{
            required:true,
            minlength:4,
            maxlength:10
        },
        emailAdress:{
            required:true,
            email:true
        },
        password:{
            minlength:6
        },
        day:{
            required:true
        },
        month:{
            required:true
        },
        year:{
            required:true
        },
        gender:{
            required:true
        }       

       },
       messages:{
        fname:{
            required:"enter first name",
            minlength:"enter min chara"
        }
       }
    })
})